cors:
  allowedMappings: ${ALLOWED_MAPPINGS}
  allowedOrigins: ${ALLOWED_ORIGINS}
  allowedMethods: ${ALLOWED_METHODS}
  allowedHeaders: ${ALLOWED_HEADERS}
  maxAge: ${MAX_AGE}
security:
  jwt:
    token:
      secret-key: ${SECRET_KEY}
      expire-length: ${EXPIRATION_TOKEN}
      refresh-expire-length: ${EXPIRATION_REFRESH_TOKEN}
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    open-in-view: false
springdoc:
  pathsToMatch: /api/v1/**
  swagger-ui:
    use-root-path: true